opt_in_rules:
  - closure_spacing
  - collection_alignment
  - discouraged_assert
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - nslocalizedstring_key
  - number_separator
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - prohibited_super_call
  - reduce_into
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - xctfail_message

disabled_rules:
  - comment_spacing
  - identifier_name
  - leading_whitespace
  - line_length
  - multiple_closures_with_trailing_closure
  - type_name

# Rule Customizations

file_header:
    forbidden_string: "Flider"
file_name:
    suffix_pattern: "Extensions"
large_tuple:
    warning: 3
    error: 4
nesting:
    type_level: 2
    function_level: 3
number_separator:
    minimum_length: 5
trailing_comma:
    mandatory_comma: true
trailing_whitespace:
    ignores_empty_lines: true
